<?php
declare(strict_types=1);

return [
    [
        'name'    => 'version',
        'title'   => 'API版本',
        'type'    => 'radio',
        'content' => ['v3' => 'V3'],
        'value'   => 'v3',
        'tip'     => '默认使用 Composer yansongda/pay V3',
    ],
    [
        'name'    => 'wechat',
        'title'   => '微信',
        'type'    => 'array',
        'value'   => [
            'appid'          => '',
            'app_id'         => '',
            'app_secret'     => '',
            'miniapp_id'     => '',
            'mch_id'         => '',
            'key'            => '',
            'key_v3'         => '',
            'public_key_id'  => '',
            'public_key'     => '/addons/yspay/certs/public_key.pem',
            'cert_client'    => '/addons/yspay/certs/apiclient_cert.pem',
            'cert_key'       => '/addons/yspay/certs/apiclient_key.pem',
            'mode'           => 'normal',
            'sub_mch_id'     => '',
            'sub_appid'      => '',
            'sub_app_id'     => '',
            'sub_miniapp_id' => '',
            'notify_url'     => '',
            'log'            => '1',
        ],
        'tip'     => '微信支付参数',
    ],
    [
        'name'    => 'alipay',
        'title'   => '支付宝',
        'type'    => 'array',
        'value'   => [
            'app_id'              => '',
            'mode'                => 'normal',
            'notify_url'          => '/addons/yspay/api/notifyx/type/alipay',
            'return_url'          => '/addons/yspay/api/returnx/type/alipay',
            'private_key'         => '',
            'signtype'            => 'cert',
            'pid'                 => '',
            'ali_public_key'      => '',
            'app_cert_public_key' => '',
            'alipay_root_cert'    => '',
            'log'                 => '1',
            'scanpay'             => '0',
        ],
        'tip'     => '支付宝参数',
    ],
];
